# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/anilreddy/Documents/C++/linux input montior"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/anilreddy/Documents/C++/linux input montior/build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/anilreddy/Documents/C++/linux input montior/build/CMakeFiles" "/home/anilreddy/Documents/C++/linux input montior/build//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/anilreddy/Documents/C++/linux input montior/build/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named input-monitor

# Build rule for target.
input-monitor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 input-monitor
.PHONY : input-monitor

# fast build rule for target.
input-monitor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input-monitor.dir/build.make CMakeFiles/input-monitor.dir/build
.PHONY : input-monitor/fast

src/device.o: src/device.cpp.o
.PHONY : src/device.o

# target to build an object file
src/device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input-monitor.dir/build.make CMakeFiles/input-monitor.dir/src/device.cpp.o
.PHONY : src/device.cpp.o

src/device.i: src/device.cpp.i
.PHONY : src/device.i

# target to preprocess a source file
src/device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input-monitor.dir/build.make CMakeFiles/input-monitor.dir/src/device.cpp.i
.PHONY : src/device.cpp.i

src/device.s: src/device.cpp.s
.PHONY : src/device.s

# target to generate assembly for a file
src/device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input-monitor.dir/build.make CMakeFiles/input-monitor.dir/src/device.cpp.s
.PHONY : src/device.cpp.s

src/event_printer.o: src/event_printer.cpp.o
.PHONY : src/event_printer.o

# target to build an object file
src/event_printer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input-monitor.dir/build.make CMakeFiles/input-monitor.dir/src/event_printer.cpp.o
.PHONY : src/event_printer.cpp.o

src/event_printer.i: src/event_printer.cpp.i
.PHONY : src/event_printer.i

# target to preprocess a source file
src/event_printer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input-monitor.dir/build.make CMakeFiles/input-monitor.dir/src/event_printer.cpp.i
.PHONY : src/event_printer.cpp.i

src/event_printer.s: src/event_printer.cpp.s
.PHONY : src/event_printer.s

# target to generate assembly for a file
src/event_printer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input-monitor.dir/build.make CMakeFiles/input-monitor.dir/src/event_printer.cpp.s
.PHONY : src/event_printer.cpp.s

src/event_reader.o: src/event_reader.cpp.o
.PHONY : src/event_reader.o

# target to build an object file
src/event_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input-monitor.dir/build.make CMakeFiles/input-monitor.dir/src/event_reader.cpp.o
.PHONY : src/event_reader.cpp.o

src/event_reader.i: src/event_reader.cpp.i
.PHONY : src/event_reader.i

# target to preprocess a source file
src/event_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input-monitor.dir/build.make CMakeFiles/input-monitor.dir/src/event_reader.cpp.i
.PHONY : src/event_reader.cpp.i

src/event_reader.s: src/event_reader.cpp.s
.PHONY : src/event_reader.s

# target to generate assembly for a file
src/event_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input-monitor.dir/build.make CMakeFiles/input-monitor.dir/src/event_reader.cpp.s
.PHONY : src/event_reader.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input-monitor.dir/build.make CMakeFiles/input-monitor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input-monitor.dir/build.make CMakeFiles/input-monitor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/input-monitor.dir/build.make CMakeFiles/input-monitor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... input-monitor"
	@echo "... src/device.o"
	@echo "... src/device.i"
	@echo "... src/device.s"
	@echo "... src/event_printer.o"
	@echo "... src/event_printer.i"
	@echo "... src/event_printer.s"
	@echo "... src/event_reader.o"
	@echo "... src/event_reader.i"
	@echo "... src/event_reader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

